---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  DJANGO_MYSQL_DATABASE: "video_archive"
  DJANGO_MYSQL_USER: video_archive
  DJANGO_MYSQL_PORT: '3306'
  CELERY_BROKER_URL: 'amqp://mq'
  S3_URL: 'http://s3:9000'
  S3_ORIGINAL_BUCKET_NAME: original
  S3_PUBLIC_BUCKET_NAME: public
  S3_THUMBNAIL_PREFIX: thumbnail
  S3_MP4_PREFIX: mp4
