---
apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  DJANGO_SECRET_KEY: 'e-(eqtpzl7bvp9h=-q64b$36&mgv_km6--ncbf=m@07c(m67op'
  DJANGO_MYSQL_PASSWORD: dmlkZW9fYXJjaGl2ZQ==
  DJANGO_MYSQL_ROOT_PASSWORD: cm9vdA==
  S3_ACCESS_KEY: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=
  S3_SECRET_KEY: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
