version: "3.5"

services:
  mq:
    image: rabbitmq:3-alpine
    container_name: mq
    ports:
      - "25672:25672"
    network_mode: host

  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
    network_mode: host

  adminer:
    image: adminer
    network_mode: host
    
  s3:
    image: minio/minio
    volumes:
      - ./minio_data:/data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    network_mode: host
      
  s3_prepare:
    image: minio/mc
    network_mode: host
    command: |
      mc mb storage/original;
      mc policy set download storage/original;
    environment:      
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
      - MC_HOST_storage="http://${MINIO_ACCESS_KEY}:${MINIO_SECRET_KEY}@s3:9000"
    depends_on:
      - s3
      
  nginx:
    image: nginx
    network_mode: host
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  app:
    build:
      context: ./django
      image: video-archive
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 --access-logfile /var/log/gunicorn-access.log video_archive.wsgi
    network_mode: host
    
  worker:
    build:
      context: ./django
      image: video-archive
    command: celery -A App worker -l info
    network_mode: host
    
      
